/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ToniraneRouteImport } from './routes/tonirane'
import { Route as ApiPublicExtractCodesRouteImport } from './routes/api/public/extract-codes'
import { Route as ApiPublicTintingInfoRouteImport } from './routes/api/public/tinting-info'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ToniraneRoute = ToniraneRouteImport.update({
  id: '/tonirane',
  path: '/tonirane',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractCodesRoute = ApiPublicExtractCodesRouteImport.update({
  id: '/api/public/extract-codes',
  path: '/api/public/extract-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTintingInfoRoute = ApiPublicTintingInfoRouteImport.update({
  id: '/api/public/tinting-info',
  path: '/api/public/tinting-info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tonirane': typeof ToniraneRoute
  '/api/public/extract-codes': typeof ApiPublicExtractCodesRoute
  '/api/public/tinting-info': typeof ApiPublicTintingInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tonirane': typeof ToniraneRoute
  '/api/public/extract-codes': typeof ApiPublicExtractCodesRoute
  '/api/public/tinting-info': typeof ApiPublicTintingInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tonirane': typeof ToniraneRoute
  '/api/public/extract-codes': typeof ApiPublicExtractCodesRoute
  '/api/public/tinting-info': typeof ApiPublicTintingInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/tonirane'
    | '/api/public/extract-codes'
    | '/api/public/tinting-info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/tonirane'
    | '/api/public/extract-codes'
    | '/api/public/tinting-info'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/tonirane'
    | '/api/public/extract-codes'
    | '/api/public/tinting-info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToniraneRoute: typeof ToniraneRoute
  ApiPublicExtractCodesRoute: typeof ApiPublicExtractCodesRoute
  ApiPublicTintingInfoRoute: typeof ApiPublicTintingInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tonirane': {
      id: '/tonirane'
      path: '/tonirane'
      fullPath: '/tonirane'
      preLoaderRoute: typeof ToniraneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-codes': {
      id: '/api/public/extract-codes'
      path: '/api/public/extract-codes'
      fullPath: '/api/public/extract-codes'
      preLoaderRoute: typeof ApiPublicExtractCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tinting-info': {
      id: '/api/public/tinting-info'
      path: '/api/public/tinting-info'
      fullPath: '/api/public/tinting-info'
      preLoaderRoute: typeof ApiPublicTintingInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToniraneRoute: ToniraneRoute,
  ApiPublicExtractCodesRoute: ApiPublicExtractCodesRoute,
  ApiPublicTintingInfoRoute: ApiPublicTintingInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
